"""
Django settings for farmacia project.
Generated by 'django-admin startproject' using Django 4.2.7.
"""

import os

# Detectar si estamos en PythonAnywhere
if 'PYTHONANYWHERE_DOMAIN' in os.environ:
    # Configuración PRODUCCIÓN (PythonAnywhere)
    DEBUG = False
    ALLOWED_HOSTS = ['laurenvanesabo.pythonanywhere.com']
    
    DATABASES = {
        'default': {
            'ENGINE': 'django.db.backends.mysql',
            'NAME': 'laurenvanesabo$default',           # Usa la BD que ya existe
            'USER': 'laurenvanesabo',                   # Tu usuario
            'PASSWORD': 'Lau123456-',          # ⚠️ PON AQUÍ LA CONTRASEÑA QUE CREASTE
            'HOST': 'laurenvanesabo.mysql.pythonanywhere-services.com',
        }
    }
    
    STATIC_ROOT = '/home/laurenvanesabo/gestion-domicilios-farmacia/static'
    
else:
    # Configuración LOCAL (con XAMPP)
    DEBUG = True
    ALLOWED_HOSTS = ['localhost', '127.0.0.1']
    
    DATABASES = {
        'default': {
            'ENGINE': 'django.db.backends.mysql',
            'NAME': 'gestion_domicilios_farmacia',      # Tu BD local en XAMPP
            'USER': 'root',
            'PASSWORD': '',                 # Normalmente vacío en XAMPP
            'HOST': 'localhost',
            'PORT': '3306',
        }
    }