# Generated by Django 4.2.7 on 2025-11-25 03:14

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Cliente',
            fields=[
                ('cliente_id', models.AutoField(primary_key=True, serialize=False)),
                ('cedula', models.CharField(max_length=20, unique=True)),
                ('nombres', models.CharField(max_length=100)),
                ('apellidos', models.CharField(max_length=100)),
                ('telefono', models.CharField(max_length=15)),
                ('direccion', models.CharField(max_length=255)),
                ('email', models.EmailField(blank=True, max_length=100, null=True)),
                ('discapacidad', models.BooleanField(default=False)),
                ('zona', models.CharField(max_length=50)),
                ('fecha_registro', models.DateTimeField(default=django.utils.timezone.now)),
                ('usuario', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Cliente',
                'verbose_name_plural': 'Clientes',
                'db_table': 'CLIENTE',
            },
        ),
        migrations.CreateModel(
            name='Pedido',
            fields=[
                ('pedido_id', models.AutoField(primary_key=True, serialize=False)),
                ('fecha_pedido', models.DateTimeField(default=django.utils.timezone.now)),
                ('fecha_asignacion', models.DateTimeField(blank=True, null=True)),
                ('fecha_entrega_estimada', models.DateTimeField(blank=True, null=True)),
                ('fecha_entrega_real', models.DateTimeField(blank=True, null=True)),
                ('estado', models.CharField(choices=[('pendiente', 'Pendiente'), ('asignado', 'Asignado'), ('en_camino', 'En Camino'), ('entregado', 'Entregado'), ('cancelado', 'Cancelado')], default='pendiente', max_length=20)),
                ('direccion_entrega', models.CharField(max_length=255)),
                ('zona_entrega', models.CharField(max_length=50)),
                ('prioridad', models.CharField(choices=[('normal', 'Normal'), ('alta', 'Alta'), ('urgente', 'Urgente')], default='normal', max_length=10)),
                ('tiempo_estimado_minutos', models.IntegerField()),
                ('tiempo_real_minutos', models.IntegerField(blank=True, null=True)),
                ('observaciones', models.TextField(blank=True, null=True)),
                ('cliente', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='domicilios.cliente')),
            ],
            options={
                'verbose_name': 'Pedido',
                'verbose_name_plural': 'Pedidos',
                'db_table': 'PEDIDO',
            },
        ),
        migrations.CreateModel(
            name='Repartidor',
            fields=[
                ('repartidor_id', models.AutoField(primary_key=True, serialize=False)),
                ('cedula', models.CharField(max_length=20, unique=True)),
                ('nombres', models.CharField(max_length=100)),
                ('apellidos', models.CharField(max_length=100)),
                ('telefono', models.CharField(max_length=15)),
                ('vehiculo', models.CharField(blank=True, max_length=50, null=True)),
                ('disponible', models.BooleanField(default=True)),
                ('zona_asignada', models.CharField(max_length=50)),
                ('capacidad_entregas', models.IntegerField(default=5)),
                ('activo', models.BooleanField(default=True)),
            ],
            options={
                'verbose_name': 'Repartidor',
                'verbose_name_plural': 'Repartidores',
                'db_table': 'REPARTIDOR',
            },
        ),
        migrations.CreateModel(
            name='ReporteEntregas',
            fields=[
                ('reporte_id', models.AutoField(primary_key=True, serialize=False)),
                ('fecha_reporte', models.DateField()),
                ('hora_salida', models.TimeField(blank=True, null=True)),
                ('hora_llegada', models.TimeField(blank=True, null=True)),
                ('hora_entrega', models.TimeField(blank=True, null=True)),
                ('tiempo_transito', models.IntegerField(blank=True, null=True)),
                ('tiempo_total', models.IntegerField(blank=True, null=True)),
                ('estado_entrega', models.CharField(choices=[('exitosa', 'Exitosa'), ('fallida', 'Fallida'), ('reprogramada', 'Reprogramada')], max_length=15)),
                ('motivo_falla', models.TextField(blank=True, null=True)),
                ('calificacion', models.IntegerField(blank=True, choices=[(1, 1), (2, 2), (3, 3), (4, 4), (5, 5)], null=True)),
                ('comentarios_cliente', models.TextField(blank=True, null=True)),
                ('pedido', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='domicilios.pedido')),
                ('repartidor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='domicilios.repartidor')),
            ],
            options={
                'verbose_name': 'Reporte de Entrega',
                'verbose_name_plural': 'Reportes de Entrega',
                'db_table': 'REPORTE_ENTREGAS',
            },
        ),
        migrations.AddField(
            model_name='pedido',
            name='repartidor',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='domicilios.repartidor'),
        ),
        migrations.CreateModel(
            name='HistorialEstados',
            fields=[
                ('historial_id', models.AutoField(primary_key=True, serialize=False)),
                ('estado_anterior', models.CharField(blank=True, max_length=50, null=True)),
                ('estado_nuevo', models.CharField(max_length=50)),
                ('fecha_cambio', models.DateTimeField(default=django.utils.timezone.now)),
                ('usuario', models.CharField(max_length=100)),
                ('pedido', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='domicilios.pedido')),
            ],
            options={
                'verbose_name': 'Historial de Estado',
                'verbose_name_plural': 'Historial de Estados',
                'db_table': 'HISTORIAL_ESTADOS',
            },
        ),
        migrations.AddIndex(
            model_name='pedido',
            index=models.Index(fields=['estado'], name='PEDIDO_estado_6315c3_idx'),
        ),
        migrations.AddIndex(
            model_name='pedido',
            index=models.Index(fields=['zona_entrega'], name='PEDIDO_zona_en_3d6feb_idx'),
        ),
        migrations.AddIndex(
            model_name='pedido',
            index=models.Index(fields=['fecha_pedido'], name='PEDIDO_fecha_p_329720_idx'),
        ),
        migrations.AddIndex(
            model_name='historialestados',
            index=models.Index(fields=['pedido', 'fecha_cambio'], name='HISTORIAL_E_pedido__b92f21_idx'),
        ),
    ]
